robot_platform_control:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  gazebo_ros_control:
    pid_gains:
      front_LW_joint:
        p: 1
        i: 0
        d: 0
      front_RW_joint:
        p: 1
        i: 0
        d: 0
  # Position and velocity Controllers ---------------------------------------
  front_LW_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_LW_joint
    # pid_gains: {p: 0.7, i: 0, d: 2}

  front_RW_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_RW_joint
    # pid_gains: {p: 0.7, i: 0, d: 2}

  back_wheel_left_bar_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_wheel_left_bar_joint
    pid: {p: 0, i: 0, d: 0}

  back_wheel_right_bar_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_wheel_right_bar_joint
    pid: {p: 0, i: 0, d: 0}

  back_RW_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: back_RW_joint
    pid: {p: 0, i: 0, d: 0}

  back_LW_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: back_LW_joint
    pid: {p: 0, i: 0, d: 0}
