robot_platform_control:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position and velocity Controllers ---------------------------------------
  back_LW_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_LW_joint
    pid: {p: 1, i: 0, d: 0}

  back_RW_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_RW_joint
    pid: {p: 1, i: 0, d: 0}

  front_LW_con_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_LW_con_joint
    pid: {p: 1, i: 0, d: 0}

  front_RW_con_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_RW_con_joint
    pid: {p: 1, i: 0, d: 0}
